name: Go

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install System Packages
      run: sudo apt-get update && sudo apt-get install -y libglfw3-dev

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...